### ISSUE TITLE
External relay streams

### ISSUE THREAD

**Issue by gammaw** [lahmacunradio/liquidsoap#340]
Related links: 
- https://github.com/AzuraCast/AzuraCast/issues/1435
- https://www.airtime.pro/secure-streams/ (Question: on the Cashmere radio page a https stream URL is embedded (see source), which is not reachable, but the http version is)

**Comment by pvj** [comment]
> We did it here [622c406](https://github.com/mmmnmnm/lahmacun/commit/622c406828bb80c2d670e80cc84f1b903c1f6bef) but we had an issue with a flood of error messages (see #403).

I'd say just for clarity is it okay if I rename this to `Relay streams`? We have achieved accepting them technically and now we are looking into (possible) bugs w/ it which is past the orig. title.

**Comment by gammaw** [comment]
Note: `input.https` is deprecated and in Liquidsoap 2.0 `input.http` should be be used for secure (https) links too. Related issue: https://github.com/savonet/liquidsoap/issues/1693

**Comment by gammaw** [comment]
Will check with LS 2.0.0 if the error messages are still there.

**Comment by gammaw** [comment]
> Will check with LS 2.0.0 if the error messages are still there.

It seems they are not (tested w/ version in Azuracast v0.17.3).

**Comment by gammaw** [comment]
Seems stable with Azuracast 0.17.7 and Liquidsoap 2.1.4 (shipped with Azuracast 0.17.7). 

See here 

https://github.com/lahmacunradio/liquidsoap/blob/a068d475690ac5a107560d8e191bd251e38548ef/azuracast/liquidsoap_custom.liq#L254

and here

https://github.com/lahmacunradio/liquidsoap/blob/a068d475690ac5a107560d8e191bd251e38548ef/azuracast/liquidsoap_custom.liq#L384
